# Generated by Django 5.2.4 on 2025-08-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationaliduser',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
