# Generated by Django 5.2.4 on 2025-08-07 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_nationaliduser_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationaliduser',
            old_name='national_id_number',
            new_name='uid',
        ),
    ]
