# Generated by Django 5.2.4 on 2025-08-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_national_id_number_nationaliduser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationaliduser',
            name='kid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
