# Generated by Django 5.2.4 on 2025-08-07 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_nationaliduser_kid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationaliduser',
            old_name='uid',
            new_name='national',
        ),
    ]
