# Generated by Django 5.2.4 on 2025-08-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_uid_nationaliduser_national'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nationaliduser',
            old_name='national',
            new_name='national_id_number',
        ),
        migrations.RemoveField(
            model_name='nationaliduser',
            name='kid',
        ),
    ]
